## 73 pandas数据切片（三）

### 数据切片 qcut ，基于分位数离散化。和分类数据有一定关系
参数 x, q, labels=None, retbins=False, precision=3, duplicates='raise'

In [1]:
import numpy  as np
import pandas as pd
from faker import Faker

fake = Faker('zh_CN')
df=pd.DataFrame(data=[ [fake.name()] for x in range(10) ],columns=['name'])

df['销售额']=np.random.randint(100,100000,size=(10, 1))
df['时间']=pd.date_range(start='2020-01-01',periods=10,freq='D')
df.insert(0,'dept',['部门1']*5+['部门2']*5)
df.insert(1,'dept1',['小部门1']*2+['小部门2']*3+['小部门3']*1+['小部门4']*4)

In [2]:
df.sort_values('销售额') # 随机生成的数据

dept dept1 name    销售额         时间
3  部门1  小部门2   刘琴  14691 2020-01-04
1  部门1  小部门1   赖刚  18554 2020-01-02
5  部门2  小部门3   王莉  25790 2020-01-06
8  部门2  小部门4  黄淑兰  30647 2020-01-09
6  部门2  小部门4   王琴  37971 2020-01-07
9  部门2  小部门4  陈秀芳  58173 2020-01-10
0  部门1  小部门1   程杨  75023 2020-01-01
7  部门2  小部门4  唐玉华  81019 2020-01-08
4  部门1  小部门2  董海燕  92386 2020-01-05
2  部门1  小部门2  周玉华  92984 2020-01-03

In [19]:
pd.qcut(df.销售额,q=4,retbins=1,precision=2,duplicates='drop') # duplicates 重复值处理，drop 删除  raise 报错。类似cut

(0      (48072.0, 79520.0]
 1    (14690.99, 27004.25]
 2      (79520.0, 92984.0]
 3    (14690.99, 27004.25]
 4      (79520.0, 92984.0]
 5    (14690.99, 27004.25]
 6     (27004.25, 48072.0]
 7      (79520.0, 92984.0]
 8     (27004.25, 48072.0]
 9      (48072.0, 79520.0]
 Name: 销售额, dtype: category
 Categories (4, interval[float64]): [(14690.99, 27004.25] < (27004.25, 48072.0] < (48072.0, 79520.0] < (79520.0, 92984.0]],
 array([14691.  , 27004.25, 48072.  , 79520.  , 92984.  ]))

In [17]:
pd.qcut(df.销售额,q=4,retbins=1,precision=2) # precision 控制精度

(0      (48072.0, 79520.0]
 1    (14690.99, 27004.25]
 2      (79520.0, 92984.0]
 3    (14690.99, 27004.25]
 4      (79520.0, 92984.0]
 5    (14690.99, 27004.25]
 6     (27004.25, 48072.0]
 7      (79520.0, 92984.0]
 8     (27004.25, 48072.0]
 9      (48072.0, 79520.0]
 Name: 销售额, dtype: category
 Categories (4, interval[float64]): [(14690.99, 27004.25] < (27004.25, 48072.0] < (48072.0, 79520.0] < (79520.0, 92984.0]],
 array([14691.  , 27004.25, 48072.  , 79520.  , 92984.  ]))

In [13]:
pd.qcut(df.销售额,q=4,labels=['1','2','3','4'],retbins=1) # retbins 给出 含分界值的数组

(0    3
 1    1
 2    4
 3    1
 4    4
 5    1
 6    2
 7    4
 8    2
 9    3
 Name: 销售额, dtype: category
 Categories (4, object): ['1' < '2' < '3' < '4'],
 array([14691.  , 27004.25, 48072.  , 79520.  , 92984.  ]))

In [12]:
pd.qcut(df.销售额,q=4,labels=['1','2','3','4']) # labels 自定义标签

0    3
1    1
2    4
3    1
4    4
5    1
6    2
7    4
8    2
9    3
Name: 销售额, dtype: category
Categories (4, object): ['1' < '2' < '3' < '4']

In [11]:
pd.qcut(df.销售额,q=4) # 基于分位数离散化。上下对照

0       (48072.0, 79520.0]
1    (14690.999, 27004.25]
2       (79520.0, 92984.0]
3    (14690.999, 27004.25]
4       (79520.0, 92984.0]
5    (14690.999, 27004.25]
6      (27004.25, 48072.0]
7       (79520.0, 92984.0]
8      (27004.25, 48072.0]
9       (48072.0, 79520.0]
Name: 销售额, dtype: category
Categories (4, interval[float64]): [(14690.999, 27004.25] < (27004.25, 48072.0] < (48072.0, 79520.0] < (79520.0, 92984.0]]

In [10]:
pd.qcut(df.销售额,q=[0,.25,.5,.75,1]) # 基于分位数离散化。q可以是list

0       (48072.0, 79520.0]
1    (14690.999, 27004.25]
2       (79520.0, 92984.0]
3    (14690.999, 27004.25]
4       (79520.0, 92984.0]
5    (14690.999, 27004.25]
6      (27004.25, 48072.0]
7       (79520.0, 92984.0]
8      (27004.25, 48072.0]
9       (48072.0, 79520.0]
Name: 销售额, dtype: category
Categories (4, interval[float64]): [(14690.999, 27004.25] < (27004.25, 48072.0] < (48072.0, 79520.0] < (79520.0, 92984.0]]

In [9]:
pd.qcut(df.销售额,q=11) # 基于分位数离散化。q 分位数

0    (70427.545, 78293.545]
1    (17851.636, 23158.727]
2      (92494.727, 92984.0]
3    (14690.999, 17851.636]
4    (85152.455, 92494.727]
5    (23158.727, 27997.727]
6    (32644.455, 39807.545]
7    (78293.545, 85152.455]
8    (27997.727, 32644.455]
9    (56336.455, 70427.545]
Name: 销售额, dtype: category
Categories (11, interval[float64]): [(14690.999, 17851.636] < (17851.636, 23158.727] < (23158.727, 27997.727] < (27997.727, 32644.455] ... (70427.545, 78293.545] < (78293.545, 85152.455] < (85152.455, 92494.727] < (92494.727, 92984.0]]