## 75 pandas值分解

### factorize 值分解，类比因式分解。这里将对象编码成枚举类型或分类变量。此处不解释其数学统计作用。
参数 values, sort=False, na_sentinel=- 1, size_hint=None

In [59]:
import numpy  as np
import pandas as pd
from faker import Faker

fake = Faker('zh_CN')
df=pd.DataFrame(data=[ [fake.name()] for x in range(10) ],columns=['name'])

df['销售额']=np.random.randint(100,100000,size=(10, 1))
df['时间']=pd.date_range(start='2020-01-01',periods=10,freq='D')
df.insert(0,'dept',['部门1']*5+['部门2']*5)
df.insert(1,'dept1',['小部门1']*2+['小部门2']*3+['小部门3']*1+['小部门4']*4)

In [64]:
df # 随机生成的数据

dept dept1 name    销售额         时间
0  部门1  小部门1   陈荣  33884 2020-01-01
1  NaN  小部门1  李凤兰  25964 2020-01-02
2  部门1  小部门2   彭晨  73442 2020-01-03
3  部门1  小部门2   许华    164 2020-01-04
4  部门1  小部门2   沈强   5508 2020-01-05
5  部门2  小部门3   刘杨  21583 2020-01-06
6  部门2  小部门4   段欣  48850 2020-01-07
7  部门2  小部门4   吴敏  93381 2020-01-08
8  部门2  小部门4  伍红梅    370 2020-01-09
9  部门2  小部门4   薛彬  51914 2020-01-10

In [76]:
pd.factorize(values=df.dept.astype('category'),sort=1,size_hint=10) # size_hint 哈希大小。

(array([ 0, -1,  0,  0,  0,  1,  1,  1,  1,  1]),
 CategoricalIndex(['部门1', '部门2'], categories=['部门1', '部门2'], ordered=False, dtype='category'))

In [74]:
codecs,uniques=pd.factorize(values=df.dept.astype('category'),sort=1) # 作用于分类类型

In [75]:
codecs,uniques # 对应两个结果

(array([ 0, -1,  0,  0,  0,  1,  1,  1,  1,  1]),
 CategoricalIndex(['部门1', '部门2'], categories=['部门1', '部门2'], ordered=False, dtype='category'))

In [73]:
pd.factorize(values=df.dept.astype('category'),sort=1) # 作用于分类类型

(array([ 0, -1,  0,  0,  0,  1,  1,  1,  1,  1]),
 CategoricalIndex(['部门1', '部门2'], categories=['部门1', '部门2'], ordered=False, dtype='category'))

In [72]:
pd.factorize(values=df.dept,sort=1) # sort 排序 

(array([ 0, -1,  0,  0,  0,  1,  1,  1,  1,  1]),
 Index(['部门1', '部门2'], dtype='object'))

In [63]:
df.iloc[1,0]=np.nan # 修改一个dept的元素值为nan

In [71]:
pd.factorize(values=df.dept) # 注意变化。na_sentinel 控制nan如何处理。默认-1

(array([ 0, -1,  0,  0,  0,  1,  1,  1,  1,  1]),
 Index(['部门1', '部门2'], dtype='object'))

In [61]:
pd.factorize(df.dept) # 分解成 0   1 对应俩部门

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1]), Index(['部门1', '部门2'], dtype='object'))