## 71 pandas数据切片（一）

### 数据切片 cut。和分类数据有一定关系
参数 x,
    bins,
    right: bool = True,
    labels=None,
    retbins: bool = False,
    precision: int = 3,
    include_lowest: bool = False,
    duplicates: str = 'raise',
    ordered: bool = True,

In [1]:
import numpy  as np
import pandas as pd
from faker import Faker

fake = Faker('zh_CN')
df=pd.DataFrame(data=[ [fake.name()] for x in range(10) ],columns=['name'])

df['销售额']=np.random.randint(100,100000,size=(10, 1))
df['时间']=pd.date_range(start='2020-01-01',periods=10,freq='D')
df.insert(0,'dept',['部门1']*5+['部门2']*5)
df.insert(1,'dept1',['小部门1']*2+['小部门2']*3+['小部门3']*1+['小部门4']*4)

In [2]:
df # 随机生成的数据

dept dept1 name    销售额         时间
0  部门1  小部门1   关俊  18369 2020-01-01
1  部门1  小部门1   董荣  53481 2020-01-02
2  部门1  小部门2   梁静  78381 2020-01-03
3  部门1  小部门2  黄淑华  53161 2020-01-04
4  部门1  小部门2  蒋凤兰  10974 2020-01-05
5  部门2  小部门3  陈丽华  36308 2020-01-06
6  部门2  小部门4   陈玲  45758 2020-01-07
7  部门2  小部门4   李瑜  73797 2020-01-08
8  部门2  小部门4   段健  93656 2020-01-09
9  部门2  小部门4   杨东  85370 2020-01-10

In [28]:
pd.cut(df.时间,2,precision=1,right=1,retbins=1,include_lowest=0,duplicates='raise') # 也可以使用在时间数据上

(0    (2019-12-31 23:47:02.400000, 2020-01-05 12:00:00]
 1    (2019-12-31 23:47:02.400000, 2020-01-05 12:00:00]
 2    (2019-12-31 23:47:02.400000, 2020-01-05 12:00:00]
 3    (2019-12-31 23:47:02.400000, 2020-01-05 12:00:00]
 4    (2019-12-31 23:47:02.400000, 2020-01-05 12:00:00]
 5                    (2020-01-05 12:00:00, 2020-01-10]
 6                    (2020-01-05 12:00:00, 2020-01-10]
 7                    (2020-01-05 12:00:00, 2020-01-10]
 8                    (2020-01-05 12:00:00, 2020-01-10]
 9                    (2020-01-05 12:00:00, 2020-01-10]
 Name: 时间, dtype: category
 Categories (2, interval[datetime64[ns]]): [(2019-12-31 23:47:02.400000, 2020-01-05 12:00:00] < (2020-01-05 12:00:00, 2020-01-10]],
 DatetimeIndex(['2019-12-31 23:47:02.400000', '2020-01-05 12:00:00',
                '2020-01-10 00:00:00'],
               dtype='datetime64[ns]', freq=None))

In [20]:
pd.cut(df.销售额,2,precision=1,right=1,labels=['低','高'],retbins=1,include_lowest=1,duplicates='raise',ordered=False) # 是否分类有序

(0    低
 1    高
 2    高
 3    高
 4    低
 5    低
 6    低
 7    高
 8    高
 9    高
 Name: 销售额, dtype: category
 Categories (2, object): ['低', '高'],
 array([10891.318, 52315.   , 93656.   ]))

In [17]:
pd.cut(df.销售额,2,precision=1,right=1,labels=['低','高'],retbins=1,include_lowest=1,duplicates='raise') # 如果有重复值，删除或者 报错。本例无

(0    低
 1    高
 2    高
 3    高
 4    低
 5    低
 6    低
 7    高
 8    高
 9    高
 Name: 销售额, dtype: category
 Categories (2, object): ['低' < '高'],
 array([10891.318, 52315.   , 93656.   ]))

In [29]:
pd.cut(df.销售额,2,precision=1,right=1,labels=['低','高'],retbins=1,include_lowest=1) # 是否包含最小点（官方英文为：第一个间隔区间是否左包含）

(0    低
 1    高
 2    高
 3    高
 4    低
 5    低
 6    低
 7    高
 8    高
 9    高
 Name: 销售额, dtype: category
 Categories (2, object): ['低' < '高'],
 array([10891.318, 52315.   , 93656.   ]))

In [11]:
pd.cut(df.销售额,2,precision=1,right=1,labels=['低','高'],retbins=1) #  返回一个array含分类数据分界值点

(0    低
 1    高
 2    高
 3    高
 4    低
 5    低
 6    低
 7    高
 8    高
 9    高
 Name: 销售额, dtype: category
 Categories (2, object): ['低' < '高'],
 array([10891.318, 52315.   , 93656.   ]))

In [8]:
pd.cut(df.销售额,2,precision=1,right=1,labels=['低','高']) #  定义分类区间的标签，方便解释等，比如这里的销售额 比较高的还是低的员工

0    低
1    高
2    高
3    高
4    低
5    低
6    低
7    高
8    高
9    高
Name: 销售额, dtype: category
Categories (2, object): ['低' < '高']

In [6]:
pd.cut(df.销售额,5,precision=1,right=1) #  right 是否含右边界

0    (10891.3, 27510.4]
1    (44046.8, 60583.2]
2    (77119.6, 93656.0]
3    (44046.8, 60583.2]
4    (10891.3, 27510.4]
5    (27510.4, 44046.8]
6    (44046.8, 60583.2]
7    (60583.2, 77119.6]
8    (77119.6, 93656.0]
9    (77119.6, 93656.0]
Name: 销售额, dtype: category
Categories (5, interval[float64]): [(10891.3, 27510.4] < (27510.4, 44046.8] < (44046.8, 60583.2] < (60583.2, 77119.6] < (77119.6, 93656.0]]

In [4]:
pd.cut(df.销售额,5,precision=1) #  precision 控制精度

0    (10891.3, 27510.4]
1    (44046.8, 60583.2]
2    (77119.6, 93656.0]
3    (44046.8, 60583.2]
4    (10891.3, 27510.4]
5    (27510.4, 44046.8]
6    (44046.8, 60583.2]
7    (60583.2, 77119.6]
8    (77119.6, 93656.0]
9    (77119.6, 93656.0]
Name: 销售额, dtype: category
Categories (5, interval[float64]): [(10891.3, 27510.4] < (27510.4, 44046.8] < (44046.8, 60583.2] < (60583.2, 77119.6] < (77119.6, 93656.0]]

In [3]:
pd.cut(df.销售额,5) #  将销售额 切成5片。结果是 分类数据，有序。给出每个元素在哪个分类“区片”

0    (10891.318, 27510.4]
1      (44046.8, 60583.2]
2      (77119.6, 93656.0]
3      (44046.8, 60583.2]
4    (10891.318, 27510.4]
5      (27510.4, 44046.8]
6      (44046.8, 60583.2]
7      (60583.2, 77119.6]
8      (77119.6, 93656.0]
9      (77119.6, 93656.0]
Name: 销售额, dtype: category
Categories (5, interval[float64]): [(10891.318, 27510.4] < (27510.4, 44046.8] < (44046.8, 60583.2] < (60583.2, 77119.6] < (77119.6, 93656.0]]